name: Publish

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Linux x64
      run: dotnet publish -c Release /p:PublishProfile=Properties\PublishProfiles\Linux64.pubxml
#      run: dotnet publish --runtime linux-x64 --self-contained true -c Release -o Pilot.Web\bin\Release\netcoreapp3.1/pilot-web_linux/
#    - name: Zip linux version to archive  
#      uses: papeloto/action-zip@v1
#      with:
#        files: Pilot.Web/bin/Release/netcoreapp3.1/publish/
#        dest: pilot-web_linux.zip
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: pilot-web_linux
        path: Pilot.Web/bin/Release/netcoreapp3.1/publish/
    - name: Publish Windows x64
      run: dotnet publish -c Release /p:PublishProfile=Properties\PublishProfiles\Windows64.pubxml
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v2
      with:
        name: pilot-web_windows
        path: Pilot.Web/bin/Release/netcoreapp3.1/publish/
    
