name: .NET Core

on:
  push:
    branches: [ release ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
    - name: Publish Linux x64
      run: dotnet publish -c Release /p:PublishProfile=Properties\PublishProfiles\Linux64.pubxml
    - name: Publish Windows x64
      run: dotnet publish -c Release /p:PublishProfile=Properties\PublishProfiles\Windows64.pubxml
    
